export const CardDetais = [
  {
    title: "Stack SSGT",
    // paraHeading: "NFT's",
    // paragraph:
    //   "For every 2500 SSGT (excl. fees) stacked you are eligible to own 1 NFT allowing you to vote on YFDAI DAO proposals that steer the direction of the project.This NFT also gives you access to the SSGT Governance Telegram Group.",
    APY: "APY",
    apyNumber: "72%",
    totalStaked: "TOTAL STAKED",
    dollar: "$823,756.27",
    totalStackers: "TOTAL STAKERS",
    number: 1317,
    ssgtStack: "SSGT STAKED",
    zero: 0,
    USD: "~ 0 USD",
    ssgtEarned: "SSGT EARNED",
    ssgtPending: "SSGT PENDING",
  },
  {
    title: "Stack SSGT",
    // paraHeading: "NFT's",
    // paragraph:
    //   "For every 2500 SSGT (excl. fees) stacked you are eligible to own 1 NFT allowing you to vote on YFDAI DAO proposals that steer the direction of the project.This NFT also gives you access to the SSGT Governance Telegram Group.",
    APY: "APY",
    apyNumber: "72%",
    totalStaked: "TOTAL STAKED",
    dollar: "$823,756.27",
    totalStackers: "TOTAL STAKERS",
    number: 1317,
    ssgtStack: "SSGT STAKED",
    zero: 0,
    USD: "~ 0 USD",
    ssgtEarned: "SSGT EARNED",
    ssgtPending: "SSGT PENDING",
  },
];
